package anjuke

type Single struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    struct {
		IsYoutui    string   `json:"isYoutui"`
		IsOff       bool     `json:"isOff"`
		ImgUrls     []string `json:"imgUrls"`
		CateID      string   `json:"cateID"`
		AjkId       string   `json:"ajk_id"`
		Tid         string   `json:"tid"`
		Sid         string   `json:"sid"`
		Paid        string   `json:"paid"`
		Lat         string   `json:"lat"`
		Lon         string   `json:"lon"`
		Ext         string   `json:"ext"`
		LocalName   string   `json:"localName"`
		ListName    string   `json:"listName"`
		Quyu        string   `json:"quyu"`
		Shangquan   string   `json:"shangquan"`
		Anxuan      bool     `json:"anxuan"`
		IsBiz       bool     `json:"isBiz"`
		CityId      string   `json:"cityId"`
		UnityCityId string   `json:"unityCityId"`
		VrUrl       string   `json:"vrUrl"`
		IsVr        string   `json:"isVr"`
		GoldOwner   struct {
			IsGoldOwner  bool   `json:"isGoldOwner"`
			NavigateText string `json:"navigateText"`
			GoldDetail   []struct {
				Title   string `json:"title"`
				Content string `json:"content"`
			} `json:"goldDetail"`
		} `json:"goldOwner"`
		HouseInfo struct {
			CityId      string `json:"city_id"`
			IsAuction   string `json:"isAuction"`
			Anxuan      bool   `json:"anxuan"`
			AllcheckMsg string `json:"allcheckMsg"`
			CateCode    string `json:"cateCode"`
			Title       string `json:"title"`
			Price       string `json:"price"`
			Tags        []struct {
				Text      string `json:"text"`
				TextColor string `json:"textColor"`
				BgColor   string `json:"bgColor"`
				Title     string `json:"title"`
				Subtitle  string `json:"subtitle"`
				DataUrl   string `json:"data_url"`
			} `json:"tags"`
			XiaoquName  string   `json:"xiaoquName"`
			Valuation   string   `json:"valuation"`
			Condition   string   `json:"condition"`
			UserId58    string   `json:"userId58"`
			Landlord    string   `json:"landlord"`
			LandlordPic string   `json:"landlordPic"`
			ImUrl       string   `json:"imUrl"`
			RoomInfo    []string `json:"roomInfo"`
			ExtendInfo  [][]struct {
				Title   string `json:"title"`
				Content string `json:"content"`
			} `json:"extendInfo"`
			BaseInfo []struct {
				Title   string `json:"title"`
				Content string `json:"content"`
			} `json:"baseInfo"`
			Address   string   `json:"address"`
			Distance  []string `json:"distance"`
			AuthStr   string   `json:"authStr"`
			LabelInfo string   `json:"labelInfo"`
			FromType  string   `json:"from_type"`
			Broker    struct {
				Id       string `json:"id"`
				Source   string `json:"source"`
				Mobile   string `json:"mobile"`
				UserId   string `json:"user_id"`
				ChatId   string `json:"chat_id"`
				Company  string `json:"company"`
				Name     string `json:"name"`
				Photo    string `json:"photo"`
				Props    string `json:"props"`
				IsActive string `json:"is_active"`
				IsGrab   string `json:"is_grab"`
				Type     string `json:"type"`
			} `json:"broker"`
			Id              string `json:"id"`
			RentType        string `json:"rent_type"`
			RoomDesc        string `json:"room_desc"`
			TypeDesc        string `json:"type_desc"`
			SourceType      string `json:"source_type"`
			Block           string `json:"block"`
			Area            string `json:"area"`
			DistanceAJK     string `json:"distanceAJK"`
			Photo           string `json:"photo"`
			Url             string `json:"url"`
			Action          string `json:"action"`
			Index           bool   `json:"index"`
			ShareUrl        string `json:"share_url"`
			IsStandardHouse string `json:"is_standard_house"`
			AjkImParm       struct {
				FromType string `json:"from_type"`
				Broker   struct {
					Id     string `json:"id"`
					Name   string `json:"name"`
					Source string `json:"source"`
				} `json:"broker"`
				WeTalkMsg string `json:"weTalkMsg"`
			} `json:"ajkImParm"`
		} `json:"houseInfo"`
		UserInfo struct {
			UserName             string        `json:"userName"`
			UserImg              string        `json:"userImg"`
			LabelInfo            string        `json:"labelInfo"`
			Company              string        `json:"company"`
			Aliascompany         string        `json:"aliascompany"`
			QualificationPhoto   string        `json:"qualificationPhoto"`
			BusinessLicenseImage string        `json:"businessLicenseImage"`
			Rating               string        `json:"rating"`
			UserEvaluate         []interface{} `json:"user_evaluate"`
			CountHouse           string        `json:"countHouse"`
			IsWorkRecordCity     bool          `json:"isWorkRecordCity"`
			RecordsInfo          []interface{} `json:"recordsInfo"`
			JumpUrl              string        `json:"jumpUrl"`
			HouseListUrl         string        `json:"houseListUrl"`
			ViolateHouseListUrl  string        `json:"violateHouseListUrl"`
			MergeBrokerUrl       string        `json:"mergeBrokerUrl"`
		} `json:"userInfo"`
		Appliance []struct {
			ImageURL string `json:"imageURL"`
			Title    string `json:"title"`
			Name     string `json:"name"`
			Have     string `json:"have"`
		} `json:"appliance"`
		HouseDetail            string        `json:"houseDetail"`
		ShengxinzuRecommendApi string        `json:"shengxinzuRecommendApi"`
		Demand                 []interface{} `json:"demand"`
		GetPhoneUrl            string        `json:"getPhoneUrl"`
		Coll                   string        `json:"coll"`
		WechatGroup            string        `json:"wechatGroup"`
		HezuInfo               string        `json:"hezuInfo"`
		LandlordUrl            string        `json:"landlordUrl"`
		Tkd                    struct {
			Title       string `json:"title"`
			Keywords    string `json:"keywords"`
			Description string `json:"description"`
		} `json:"tkd"`
		RecomNqArea struct {
			Infolist []struct {
				Infoid          string `json:"infoid"`
				CateName        string `json:"cateName"`
				CateID          string `json:"cateID"`
				Title           string `json:"title"`
				Price           string `json:"price"`
				Img             string `json:"img"`
				Unit            string `json:"unit"`
				Coll            string `json:"coll"`
				SubwayDistance  string `json:"subwayDistance"`
				FangwuLiangDian []struct {
					Text string `json:"text"`
				} `json:"fangwuLiangDian"`
				Area            string `json:"area"`
				Toward          string `json:"toward"`
				Shangquan       string `json:"shangquan"`
				IsAnxuan        string `json:"isAnxuan"`
				Location        bool   `json:"location"`
				SourceType      string `json:"source_type"`
				Isauction       string `json:"isauction"`
				AuctionShowText string `json:"auctionShowText"`
				LegoAuction     string `json:"legoAuction"`
				Tid             string `json:"tid"`
				IsLiving        bool   `json:"isLiving"`
				IsVR            bool   `json:"isVR"`
				DistanceDesc    string `json:"distanceDesc"`
				IsGoldOwner     bool   `json:"isGoldOwner"`
				Shengxinzu      string `json:"shengxinzu"`
				Recommend       string `json:"recommend"`
				Soj             struct {
					Infoid              string `json:"infoid"`
					Houseid             string `json:"houseid"`
					GTID                string `json:"GTID"`
					IsBiz               bool   `json:"is_biz"`
					IsDown              string `json:"is_down"`
					Slot                string `json:"slot"`
					Sid                 string `json:"sid"`
					AdType              string `json:"ad_type"`
					IsBusiness          string `json:"is_business"`
					Gpos                string `json:"gpos"`
					Pos                 string `json:"pos"`
					Shengxinzu          string `json:"shengxinzu"`
					Shidiheyanzhuangtai string `json:"shidiheyanzhuangtai"`
					Qingheyanzhuangtai  string `json:"qingheyanzhuangtai"`
					Recomshowlog        string `json:"recomshowlog"`
					Tid                 string `json:"tid"`
					Anxuan              string `json:"anxuan"`
					Qiyeanxuan          string `json:"qiyeanxuan"`
					IsVr                string `json:"isVr"`
					InfoType            string `json:"info_type"`
				} `json:"soj"`
			} `json:"infolist"`
		} `json:"recom_nq_area"`
		Activity struct {
			Switch bool `json:"switch"`
		} `json:"activity"`
		PhoneExtraParam string `json:"phone_extraParam"`
		CollectionInfo  struct {
			DataType string `json:"data_type"`
			DataId   string `json:"data_id"`
			DataInfo struct {
				FavType    string `json:"fav_type"`
				DataType   string `json:"data_type"`
				DataId     string `json:"data_id"`
				Id         string `json:"id"`
				Name       string `json:"name"`
				Price      string `json:"price"`
				Housetype  string `json:"housetype"`
				Areanum    string `json:"areanum"`
				ImageUrl   string `json:"imageUrl"`
				Region     string `json:"region"`
				Block      string `json:"block"`
				SourceType string `json:"source_type"`
				RentType   string `json:"rent_type"`
				IsAuction  string `json:"isAuction"`
				CityId     string `json:"cityId"`
				Desc       string `json:"desc"`
				JumpPath   string `json:"jumpPath"`
				JumpAction string `json:"jumpAction"`
				Prop       struct {
					Des     string `json:"des"`
					HasPano string `json:"hasPano"`
					Img     string `json:"img"`
					Info    struct {
						CityID     string `json:"cityID"`
						IsAuction  string `json:"isAuction"`
						PropertyID string `json:"propertyID"`
						SourceType string `json:"sourceType"`
						Type       string `json:"type"`
					} `json:"info"`
					Name      string `json:"name"`
					Price     string `json:"price"`
					TradeType string `json:"tradeType"`
					Type      string `json:"type"`
					Url       string `json:"url"`
				} `json:"prop"`
				DataType1 string `json:"dataType"`
			} `json:"data_info"`
		} `json:"collectionInfo"`
		SojEp struct {
			AbTest              string `json:"ab_test"`
			Cate2               string `json:"cate2"`
			Cate1               string `json:"cate1"`
			GTID                string `json:"GTID"`
			PGTID               string `json:"PGTID"`
			IsBiz               bool   `json:"is_biz"`
			IsDown              string `json:"is_down"`
			Slot                string `json:"slot"`
			Sid                 string `json:"sid"`
			IsBusiness          string `json:"is_business"`
			AdType              string `json:"ad_type"`
			Gpos                string `json:"gpos"`
			Pos                 string `json:"pos"`
			Shengxinzu          string `json:"shengxinzu"`
			Brokerid            string `json:"brokerid"`
			Shidiheyanzhuangtai string `json:"shidiheyanzhuangtai"`
			Qingheyanzhuangtai  string `json:"qingheyanzhuangtai"`
			Recomshowlog        string `json:"recomshowlog"`
			Pagesource          string `json:"pagesource"`
			Tid                 string `json:"tid"`
			Os                  string `json:"os"`
			Anxuan              string `json:"anxuan"`
			Qiyeanxuan          string `json:"qiyeanxuan"`
			ListKeywords        struct {
				Search struct {
					Keyword string `json:"keyword"`
				} `json:"search"`
				Filter []interface{} `json:"filter"`
			} `json:"list_keywords"`
			Infoid    string `json:"infoid"`
			InfoType  string `json:"info_type"`
			Userid    string `json:"userid"`
			UserType  string `json:"user_type"`
			Houseid   string `json:"houseid"`
			Cityid158 string `json:"cityid1_58"`
		} `json:"soj_ep"`
		SojCp struct {
			V               string `json:"v"`
			Channel         string `json:"channel"`
			UserId          string `json:"userId"`
			UserType        string `json:"userType"`
			TradeType       string `json:"tradeType"`
			ProId           string `json:"proId"`
			COMMID          string `json:"COMMID"`
			BrokerId        string `json:"brokerId"`
			BrokerType      string `json:"brokerType"`
			HpType          string `json:"hpType"`
			Entry           string `json:"entry"`
			Uniqid          string `json:"uniqid"`
			AreaId          string `json:"areaId"`
			LocalId         string `json:"localId"`
			Invalid         string `json:"invalid"`
			Ir              string `json:"ir"`
			HpPage          string `json:"hpPage"`
			Agent           string `json:"agent"`
			Cookie          string `json:"cookie"`
			Ip              string `json:"ip"`
			ExpireTimestamp string `json:"expireTimestamp"`
		} `json:"soj_cp"`
		Uniqid string `json:"uniqid"`
	} `json:"data"`
}
