package leyoujia

type Info struct {
	Data struct {
		ZfList struct {
			Data []struct {
				AreaCode   string `json:"areaCode"`
				AreaName   string `json:"areaName"`
				Attributes struct {
				} `json:"attributes"`
				BasicPackage         string      `json:"basicPackage"`
				BuildingArea         float64     `json:"buildingArea"`
				CityCode             string      `json:"cityCode"`
				CityName             string      `json:"cityName"`
				Collected            interface{} `json:"collected"`
				ComAddress           string      `json:"comAddress"`
				ComAlias             string      `json:"comAlias"`
				ComId                int         `json:"comId"`
				ComName              string      `json:"comName"`
				CompletionDate       *int64      `json:"completionDate"`
				CompletionDateString string      `json:"completionDateString"`
				DeployDate           int64       `json:"deployDate"`
				DgId                 int         `json:"dgId"`
				DpCount              int         `json:"dpCount"`
				Fitment              string      `json:"fitment"`
				FloorHeightString    string      `json:"floorHeightString"`
				Furniture            string      `json:"furniture"`
				FurnitureAndPackage  string      `json:"furnitureAndPackage"`
				FxWorkerId           string      `json:"fxWorkerId"`
				HasAlbum             bool        `json:"hasAlbum"`
				HasElevator          int         `json:"hasElevator"`
				HasKey               bool        `json:"hasKey"`
				HouseAge             interface{} `json:"houseAge"`
				HouseId              int         `json:"houseId"`
				HouseNumber          string      `json:"houseNumber"`
				HouseType            string      `json:"houseType"`
				ImageUrl             string      `json:"imageUrl"`
				IndoorArea           float64     `json:"indoorArea"`
				IsNearSubway         *int        `json:"isNearSubway"`
				IsOutsideShow        int         `json:"isOutsideShow"`
				JointRent            int         `json:"jointRent"`
				Kitchen              int         `json:"kitchen"`
				Latitude             float64     `json:"latitude"`
				Layer                int         `json:"layer"`
				LayerHeight          int         `json:"layerHeight"`
				LayoutId             int         `json:"layoutId"`
				Longitude            float64     `json:"longitude"`
				LpWorkerId           string      `json:"lpWorkerId"`
				LupDate              int64       `json:"lupDate"`
				NearbyTraffic        string      `json:"nearbyTraffic"`
				Orientation          string      `json:"orientation"`
				Parlor               int         `json:"parlor"`
				Payment              string      `json:"payment"`
				PaymentWay           string      `json:"paymentWay"`
				PlaceCode            string      `json:"placeCode"`
				PlaceName            string      `json:"placeName"`
				Portal               int         `json:"portal"`
				PropertyType         string      `json:"propertyType"`
				RailIds              []int       `json:"railIds"`
				RecommendReasons     string      `json:"recommendReasons"`
				RecommendScore       interface{} `json:"recommendScore"`
				RecommendType        *int        `json:"recommendType"`
				Remark               string      `json:"remark"`
				RentMark             float64     `json:"rentMark"`
				RentPrice            float64     `json:"rentPrice"`
				RentRankScore        int         `json:"rentRankScore"`
				RentUnitPrice        interface{} `json:"rentUnitPrice"`
				RightYear            string      `json:"rightYear"`
				Room                 int         `json:"room"`
				SaleStatus           int         `json:"saleStatus"`
				Sign                 interface{} `json:"sign"`
				SkWorkerId           string      `json:"skWorkerId"`
				StarHouse            bool        `json:"starHouse"`
				State                int         `json:"state"`
				StationIds           []int       `json:"stationIds"`
				SurfaceLayer         int         `json:"surfaceLayer"`
				SxHsl                bool        `json:"sxHsl"`
				SxWorkerId           string      `json:"sxWorkerId"`
				Tags                 string      `json:"tags"`
				TgHouse              bool        `json:"tgHouse"`
				TgId                 interface{} `json:"tgId"`
				TgLocationId         interface{} `json:"tgLocationId"`
				TgType               interface{} `json:"tgType"`
				TgWorkerId           string      `json:"tgWorkerId"`
				Title                string      `json:"title"`
				Toilet               int         `json:"toilet"`
				UniqueKey            string      `json:"uniqueKey"`
				VideoHouse           bool        `json:"videoHouse"`
				VrHouse              bool        `json:"vrHouse"`
				YsWorkerId           string      `json:"ysWorkerId"`
				ZrWorkerId           string      `json:"zrWorkerId"`
			} `json:"data"`
			PageNo      int `json:"pageNo"`
			PageSize    int `json:"pageSize"`
			TotalPage   int `json:"totalPage"`
			TotalRecord int `json:"totalRecord"`
		} `json:"zfList"`
		SuggestKey       interface{}   `json:"suggestKey"`
		Topics           []interface{} `json:"topics"`
		PreferenceLabels []struct {
			CityCode   string `json:"cityCode"`
			CreateTime int64  `json:"createTime"`
			Id         int    `json:"id"`
			LabelName  string `json:"labelName"`
			Type       int    `json:"type"`
			UpdateTime int64  `json:"updateTime"`
		} `json:"preferenceLabels"`
	} `json:"data"`
	ErrorCode   string `json:"errorCode"`
	ErrorMsg    string `json:"errorMsg"`
	ErrorMsgDev string `json:"errorMsgDev"`
	Success     bool   `json:"success"`
	Tips        string `json:"tips"`
}
